homeassistant:
  allowlist_external_dirs:
    - "/config/scripts/tplink-kasa/devices"

light:
  - platform: template
    lights:
      light1:
        level_template: "{{ states('sensor.light1_brightness') | int * 2.55 }}"
        value_template: "{{ states('sensor.light1_state')|int > 0 }}"
        temperature_template: "{{ states('sensor.light1_light_temp', 'deg') | int}}"
        color_template: "({{states('sensor.light1_hue') | int}}, {{states('sensor.light1_saturation') | int}})"
        friendly_name: "YOUR_LIGHT_NAME"
        turn_on:
          - service: shell_command.sh_light_on
            data:
              lightid: "YOUR_LIGHT_ID - from kasa-devices"
          - service: homeassistant.update_entity
            entity_id: sensor.light1_state
        turn_off:
          - service: shell_command.sh_light_off
            data:
              lightid: "YOUR_LIGHT_ID - from kasa-devices"
          - service: homeassistant.update_entity
            entity_id: sensor.light1_state
        set_level:
          - service: shell_command.sh_light_brightness
            data:
              lightlevel: "{{ (brightness / 2.55) | int }}"
              lightid: "YOUR_LIGHT_ID - from kasa-devices"
          - service: homeassistant.update_entity
            entity_id: sensor.light1_brightness              
        set_temperature: 
          - service: shell_command.sh_light_temp
            data:
              ctemp: "{{ ( 11866 - (18.7 * color_temp)) | int }}"
              lightid: "YOUR_LIGHT_ID - from kasa-devices"
          - service: homeassistant.update_entity
            entity_id: sensor.light1_light_temp              
        set_color:
          - service: shell_command.sh_light_hue_sat
            data:
              hue: "{{ h }}"
              sat: "{{ s }}"
              lightid: "YOUR_LIGHT_ID - from kasa-devices"      
          - service: homeassistant.update_entity
            entity_id: sensor.light1_hue              
          - service: homeassistant.update_entity
            entity_id: sensor.light1_saturation              

switch:
  - platform: template
    switches:
      tplink_strip1_plug1:
        value_template: "{{ is_state('sensor.strip1_plug1', '1') }}"
        turn_on:
          - service: shell_command.sh_switch_change
            data:
              onoff: "1"
              stripid: "STRIP_ID"
              plugid: "PLUG1_ID"
          - service: homeassistant.update_entity
            entity_id: sensor.strip1_plug1
        turn_off:
          - service: shell_command.sh_switch_change
            data:
              onoff: "0"
              stripid: "STRIP_ID"
              plugid: "PLUG1_ID"
          - service: homeassistant.update_entity
            entity_id: sensor.strip1_plug1
  - platform: template
    switches:
      tplink_strip1_plug2:
        value_template: "{{ is_state('sensor.strip1_plug2', '1') }}"
        turn_on:
          - service: shell_command.sh_switch_change
            data:
              onoff: "1"
              stripid: "STRIP_ID"
              plugid: "PLUG2_ID"
          - service: homeassistant.update_entity
            entity_id: sensor.strip1_plug2
        turn_off:
          - service: shell_command.sh_switch_change
            data:
              onoff: "0"
              stripid: "STRIP_ID"
              plugid: "PLUG2_ID"
          - service: homeassistant.update_entity
            entity_id: sensor.strip1_plug2
  - platform: template
    switches:
      tplink_strip1_plug3:
        value_template: "{{ is_state('sensor.strip1_plug3', '1') }}"
        turn_on:
          - service: shell_command.sh_switch_change
            data:
              onoff: "1"
              stripid: "STRIP_ID"
              plugid: "PLUG3_ID"
          - service: homeassistant.update_entity
            entity_id: sensor.strip1_plug3
        turn_off:
          - service: shell_command.sh_switch_change
            data:
              onoff: "0"
              stripid: "STRIP_ID"
              plugid: "PLUG3_ID"
          - service: homeassistant.update_entity
            entity_id: sensor.strip1_plug3

shell_command:
  sh_light_on: bash /config/scripts/tplink-kasa/setLightState.sh id={{ lightid }} on=1
  sh_light_off: bash /config/scripts/tplink-kasa/setLightState.sh id={{ lightid }} on=0
  sh_light_brightness: bash /config/scripts/tplink-kasa/setLightState.sh id={{ lightid }} b={{ lightlevel }}
  sh_light_temp: bash /config/scripts/tplink-kasa/setLightState.sh id={{ lightid }} ctemp={{ ctemp }}
  sh_light_hue_sat: bash /config/scripts/tplink-kasa/setLightState.sh id={{ lightid }} hue={{ hue }} sat={{ sat }} ctemp=0
  sh_switch_change: bash /config/scripts/tplink-kasa/setStripSwitchState.sh stripid={{ stripid }} plugid={{ plugid }} onoff={{ onoff }}
  
sensor:
  - platform: file
    name: 'light1_saturation'
    file_path: /config/scripts/tplink-kasa/devices/YOUR_LIGHT_ID.txt
    value_template: >
      {{ (value.split(',')[0] | int) }}
  - platform: file
    name: 'light1_brightness'
    file_path: /config/scripts/tplink-kasa/devices/YOUR_LIGHT_ID.txt
    value_template: >
      {{ (value.split(',')[1] | int) }}
  - platform: file
    name: 'light1_hue'
    file_path: /config/scripts/tplink-kasa/devices/YOUR_LIGHT_ID.txt
    value_template: >
      {{ (value.split(',')[2] | int) }}
  - platform: file
    name: 'light1_state'
    file_path: /config/scripts/tplink-kasa/devices/YOUR_LIGHT_ID.txt
    value_template: >
      {{ (value.split(',')[3] | int) }}
  - platform: file
    name: 'light1_light_temp'
    file_path: /config/scripts/tplink-kasa/devices/YOUR_LIGHT_ID.txt
    value_template: >
      {{ (value.split(',')[4] | int) }}

  - platform: file
    name: 'strip1_plug1'
    file_path: /config/scripts/tplink-kasa/devices/PLUG1_ID.txt
    value_template: >
      {{ (value.split(',')[0] | int) }}
  - platform: file
    name: 'strip1_plug2'
    file_path: /config/scripts/tplink-kasa/devices/PLUG2_ID.txt
    value_template: >
      {{ (value.split(',')[0] | int) }}
  - platform: file
    name: 'strip1_plug3'
    file_path: /config/scripts/tplink-kasa/devices/PLUG3_ID.txt
    value_template: >
      {{ (value.split(',')[0] | int) }}      